config/routes.rb
Rails.application.routes.draw do

  resources :fat_tests

  devise_for :users
    
  resources :boards do
    resources :boxes   
    resources :logs
  end

  resources :boxes do
    resources :boards
    resources :machines  
    resources :logs
  end
    
  resources :machines do
    resources :boxes
    resources :boards 
    resources :logs
    resources :fat_tests 
  end    

  resources :sites do
    resources :machines    
    resources :boxes 
    resources :boards  
    resources :logs 
  end 

  resources :customers do
    resources :machines    
    resources :boxes  
  end 
  
         
    
  root to: "machines#index"
    
end    

app/models/box.rb
class Box < ActiveRecord::Base
    # Field Validations
    validates :box_sn, format: { with: /\d{1,2}\-\d{3}/, message: "Please enter valid serial number." }
    
    has_many :logs, as: :logable
    
    belongs_to :board
    
    has_one :machine
    
    accepts_nested_attributes_for :board, :logs
    
    # Status
    enum servicestatus: [ :Service, :OK ] 
    
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
    
    before_action :authenticate_user!
    
  def index
    @boxes = Box.all
    @boards = Board.all
    @machines = Machine.all
  end

  def show 
    @box = Box.find(params[:id])
    @machines = Machine.all
  end

  def new
    @boards = Board.all 
    @box = Box.new 
  end
    
  def create
    @boards = Board.all 
    @box = Box.new(box_params) 
    if @box.save         
         flash[:notice] = "Box <b>#{ @box.box_sn }</b> has been saved successfully."
      redirect_to(boxes_path, :notice => "Box <b>#{ @box.box_sn }</b> has been saved successfully.")
    else
      render(:new, :error => @box.errors)
    end    
  end

  def edit
    @boards = Board.all 
    @box = Box.find(params[:id])
  end

  def update
    @box = Box.find(params[:id])
    if @box.update_attributes(box_params)
      redirect_to boxes_path, notice: "The box has been updated."
    end  
  end

def destroy
    @box = Box.find(params[:id])
    @box.destroy
  end
    
    
private
    
  def box_params
    params.require(:box).permit!
  end

    
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_boxlogs.erb
<h3>Box Logs</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Observation</th>
      <th>Action</th>
      <th>Assigned To</th>
	  <th>Date Submitted</th>    
      <th>Status</th>    
      <td>&nbsp;</td>
    </tr>
  </thead>
  <% if @box.logs.count > 0 %>
    
    <% @box.logs.order([created_at: :desc]).each do |log| %> 
        
    <% if log.status == "open"  %>
        <tr class="warning row-fluid">
            <td><%= log.observation %></td>
            <td><%= log.action %></td>
            <td><%= log.created_at.strftime("%F") %></td>
		    <td><%= log.assignedtouser %></td>
            <td><%= log.status.humanize %></td>  
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i> View'.html_safe, board_log_path(@board, log), class: "btn" %><%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_board_log_path(@board, log), class: "btn" %></td> 
        </tr>
      <% else %>
        <tr class="default row-fluid">
            <td><%= log.observation %></td>
            <td><%= log.action %></td>
            <td><%= log.created_at.strftime("%F") %></td>
		    <td><%= log.assignedtouser %></td>
            <td><%= log.status.humanize %></td>  
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i> View'.html_safe, board_log_path(@board, log), class: "btn" %><%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_board_log_path(@board, log), class: "btn" %></td>
        </tr>
     <% end %>
       
    <% end %>    
<% else %>
    <tr>
      <td colspan="7">No logs found for this box.</td>
    </tr>
  <% end %>
</table>

app/views/boxes/_form.html.erb
<%= bootstrap_form_for(@box, layout: :horizontal )  do |f| %>
    <%= f.text_field :box_sn, label: "Serial Number", placeholder: "XX - XXX", label_col: "col-sm-2", control_col: "col-sm-3", help: "|STC version| - |box number|" %>
    <%= f.collection_select(:board_id, Board.all, :id, :board_sn, label: "Board", label_col: "col-sm-2", control_col: "col-sm-2") %>
	
<%= f.form_group do %>
    <div class="well col-md-4" >
      <%= f.submit class: "btn btn-default" %>    
      <%= link_to "Cancel", boxes_path(@box), class: "btn btn-default" %>
    </div>
 <% end %>
<% end %>

app/views/boxes/_infobox.html.erb
 <div class = "panel panel-default">
   <div class = "panel-heading"> 
      <p>Box Information</p>
   </div>
    <div class =  "panel-body">
        <h1>Box: <%= @box.box_sn %></h1>
        <h2>Board: <%= @box.board.board_sn %></h2>
         <%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_box_path(@box), class: "btn" %> 
    </div>
</div>  

app/views/boxes/_statusbox.html.erb
 <div class = "panel panel-default">
   <div class = "panel-heading"> 
      <p>Status Information</p>
   </div>
    <div class =  "panel-body">
        <h1>Box Status: <%= @box.servicestatus %></h1>
        <h2>Board Status: <%= @box.board.servicestatus %></h2> 
    </div>
</div>  

app/views/boxes/create.html.erb
<h1>Boxes#create</h1>
<p>Find me in app/views/boxes/create.html.erb</p>

app/views/boxes/edit.html.erb
<h1>Editing Box: <%= @box.box_sn%> </h1>
<%= render "form" %>

app/views/boxes/index.html.erb
<h1>Boxes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Box SN</th>
      <th>Board SN</th>
      <th>Firmware Version</th>
      <th>Service Status</th>    
      <th>Number of Logs</th>
	  <th>Created On</th>
      <th>Last Update</th>     
    </tr>
  </thead>
  <tbody>
    <% if @boxes.count == 0 %>
      <tr>
        <td colspan="6">
          No boxes found.  Click the button below to add a new one.
        </td>
      </tr>
    <% else %>
      <% @boxes.each do |box| %>

        <tr class = "default">
          <td><%= link_to box.box_sn, box %></td>
          <td><%= box.board.board_sn %> </td> 
          <td><%= box.board.firmware %> </td>  
		  <td><%= box.servicestatus %> </td>
          <td><%= box.logs.count %></td>
		  <td><%= box.updated_at.strftime("%F") %></td>
          <td><%= box.created_at.strftime("%F") %></td>
        </tr>
      
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="well">
<%= link_to "New Box", new_box_path, class: "btn btn-default" %>
</div>

app/views/boxes/new.html.erb
<h1>New Box</h1>
<%= render "form" %>

app/views/boxes/show.html.erb
<div class= "row">
    <div class= "col-md-6">
      <%= render "infobox"%>
    </div>
    <div class= "col-md-6">
      <%= render "statusbox"%>
    </div>     
</div>   


<hr />

<%= render "boxlogs" %>

<div class="well">
  <%= link_to "New Log", new_box_log_path(@box), class: "btn btn-default" %>
  <%= link_to "Back to Boxes", boxes_path(@boxes), class: "btn btn-default" %>    
</div>

app/views/boxes/update.html.erb
<h1>Boxes#update</h1>
<p>Find me in app/views/boxes/update.html.erb</p>