config/routes.rb
Rails.application.routes.draw do

  resources :fat_tests

  devise_for :users
    
  resources :boards do
    resources :boxes   
    resources :logs
  end

  resources :boxes do
    resources :boards
    resources :machines  
    resources :logs
  end
    
  resources :machines do
    resources :boxes
    resources :boards 
    resources :logs
    resources :fat_tests 
  end    

  resources :sites do
    resources :machines    
    resources :boxes 
    resources :boards  
    resources :logs 
  end 

  resources :customers do
    resources :machines    
    resources :boxes  
  end 
  
         
    
  root to: "machines#index"
    
end    

app/models/board.rb
class Board < ActiveRecord::Base
    # Field Validations
     validates :board_sn, format: { with: /\d{5}/, message: "Please enter valid serial number." }
     validates :firmware, format: { with: /\d{1,2}\.\d{1,2}\.\d{1,2}/, message: "Please enter valid firmware version." }

    
    # Logs
    has_many :logs, as: :logable
    
    # Boxes
    has_one :box
    
    # Status
    enum servicestatus: [ :Service, :OK ]  

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
 
    before_action :authenticate_user!
    
  def index
    @machines = Machine.all
    @boxes = Box.all
    @boards = Board.all
  end

    
  def show
    @board = Board.find(params[:id])
    @users = User.all  
  end

  def new
    @board = Board.new  
  end

  def create
    @board = Board.new(board_params)
    if @board.save         
         flash[:notice] = "Board has been saved successfully."
      redirect_to(boards_path, :notice => "Board has been saved successfully.")
    else
      render(:new, :error => @board.errors)
    end    
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @boards = Board.all
    @board = Board.find(params[:id])
    if @board.update_attributes(board_params)
      redirect_to boards_path, notice: "The board has been updated"
    end  
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
  end
    
    
private
  def board_params
    params.require(:board).permit!
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_boardlogs.html.erb
<h3>Board Logs</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Observation</th>
      <th>Action</th>
      <th>Assigned To</th>
	  <th>Date Submitted</th>    
      <th>Status</th>    
      <td>&nbsp;</td>
    </tr>
  </thead>
   <% if @board.logs.count > 0 %>
    
    <% @board.logs.order([created_at: :desc]).each do |log| %>
     <% if log.status == "open"  %>
        <tr class="warning row-fluid">
            <td><%= log.observation %></td>
            <td><%= log.action %></td>
            <td><%= log.created_at.strftime("%F") %></td>
		    <td><%= log.assignedtouser %></td>
            <td><%= log.status.humanize %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i> View'.html_safe, board_log_path(@board, log), class: "btn" %><%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_board_log_path(@board, log), class: "btn" %></td> 
        </tr>
      <% else %>
        <tr class="default row-fluid">
            <td><%= log.observation %></td>
            <td><%= log.action %></td>
            <td><%= log.created_at.strftime("%F") %></td>
		    <td><%= log.assignedtouser %></td>
            <td><%= log.status.humanize %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i> View'.html_safe, board_log_path(@board, log), class: "btn" %><%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_board_log_path(@board, log), class: "btn" %></td> 
        </tr>
     <% end %>
    
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No logs found for this board.  Click the 'New Log' button to create a new log.</td>
    </tr>
  <% end %>
</table>

app/views/boards/_form.html.erb
<%= bootstrap_form_for(@board, layout: :horizontal )  do |f| %>
    <%= f.text_field :board_sn, label: "Serial Number", placeholder: "XXXXX.", help:"|STC version, board number|", label_col: "col-md-2", control_col: "col-sm-3" %>
    <%= f.text_field :firmware, label: "Firmware Version", placeholder: "Enter version xx.xx.xx", label_col: "col-sm-2", control_col: "col-md-3" %>


<%= f.form_group do %>
    <div class="well col-md-4" >
      <%= f.submit class: "btn btn-default" %>    
      <%= link_to "Cancel", boards_path(@board), class: "btn btn-default" %>
    </div>
 <% end %>
<% end %>

app/views/boards/_infobox.html.erb
 <div class = "panel panel-default">
   <div class = "panel-heading"> 
      <p>Board Information</p>
   </div>
    <div class =  "panel-body">
        <h1>Board: <%= @board.board_sn %></h1>
        <h2>Firmware Version: <%= @board.firmware %></h2>
        <%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_board_path(@board), class: "btn" %> 
    </div>
</div>  

app/views/boards/_statusbox.html.erb
 <div class = "panel panel-default">
   <div class = "panel-heading"> 
      <p>Status Information</p>
   </div>

	
			<div class="default">
			   <div class =  "panel-body">	
	        	  <h2>Board Status: <%= @board.servicestatus %></h2>
			  </div>	  
			</div>
			
    </div>
</div>  

app/views/boards/create.html.erb
<h1>Boards#create</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/edit.html.erb
<h1>Editing Board: <%= @board.board_sn %></h1>
<%= render "form" %>

app/views/boards/index.html.erb
<h1>Boards</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Board SN</th>
      <th>Firmware Version</th>
      <th>Service Status</th>    
      <th>Number of Logs</th>
      <th>Created On</th>     	  
      <th>Last Update</th>     
    </tr>
  </thead>
  <tbody>
    <% if @boards.count == 0 %>
      <tr>
        <td colspan="6">
          No boards found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @boards.each do |board| %>
	  
            <tr class = "default">
              <td><%= link_to "#{board.board_sn}", board %></td>			  
              <td><%= board.firmware %> </td>
              <td><%= board.servicestatus %></td>     
              <td><%= board.logs.count %></td>
			  <td><%= board.created_at.strftime("%F") %></td>
              <td><%= board.updated_at.strftime("%F") %></td> 
              </td>
            </tr>
        
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="well">
<%= link_to "New Board", new_board_path, class: "btn btn-default " %>
</div>

app/views/boards/new.html.erb
<h1>Create a New Board</h1>
<%= render "form" %>

app/views/boards/show.html.erb
<div class = "container">
<div class= "row">
    <div class= "col-md-6">
      <%= render "infobox"%>
    </div>
    <div class= "col-md-6">
      <%= render "statusbox"%>
    </div>     
</div>   



<hr />
 
<%= render "boardlogs" %>


<div class="well">
  <%= link_to "New Log", new_board_log_path(@board), class: "btn btn-default" %>
  <%= link_to "Back to Boards", boards_path(@boards), class: "btn btn-default" %>     
</div>
</div>

app/views/boards/update.html.erb
<h1>Boards#update</h1>
<p>Find me in app/views/boards/update.html.erb</p>