config/routes.rb
Rails.application.routes.draw do

  resources :fat_tests

  devise_for :users
    
  resources :boards do
    resources :boxes   
    resources :logs
  end

  resources :boxes do
    resources :boards
    resources :machines  
    resources :logs
  end
    
  resources :machines do
    resources :boxes
    resources :boards 
    resources :logs
    resources :fat_tests 
  end    

  resources :sites do
    resources :machines    
    resources :boxes 
    resources :boards  
    resources :logs 
  end 

  resources :customers do
    resources :machines    
    resources :boxes  
  end 
  
         
    
  root to: "machines#index"
    
end    

app/models/machine.rb
class Machine < ActiveRecord::Base
    # Field Validations
    validates :machine_sn, format: { with: /\S{6}/, message: "Please add PV or HS." }
    
  
    has_many :logs, as: :logable
    
    has_many :fat_tests
    
    belongs_to :box
    
    has_one :site
    
    accepts_nested_attributes_for :box, :logs
     
    enum servicestatus: [ :Service, :OK ] 

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
    
    before_action :authenticate_user!
    
  def index
    @machines = Machine.all
    @boxes = Box.all
    @boards = Board.all
    @sites = Site.all
    @fat_tests = FatTest.all    
  end

  def show 
    @machine = Machine.find(params[:id])
    @sites = Site.all
    @fat_tests = FatTest.all  
  end

  def new
    @boxes = Box.all
    @machine = Machine.new 
  end
    
  def create
    @machine = Machine.new(machine_params) 
    if @machine.save         
         flash[:notice] = "Box <b>#{ @machine.machine_sn }</b> has been saved successfully."
      redirect_to(machines_path, :notice => "Box <b>#{ @machine.machine_sn }</b> has been saved successfully.")
    else
      render(:new, :error => @machine.errors)
    end  
  end

  def edit
    @machine = Machine.find(params[:id])
    @fat_tests = FatTest.all    
  end

  def update
    @machine = Machine.find(params[:id])
    if @machine.update_attributes(machine_params)
      redirect_to machines_path, notice: "The machine has been updated."
    end  
  end

  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy
  end
    
#  def service 
#    if @machine.logs.status == "open"
#     @machine.servicestatus == "Service"
#    end 
#  end      
    
    
private
    
  def machine_params
    params.require(:machine).permit!
  end
    
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= bootstrap_form_for(@machine, layout: :horizontal)  do |f| %>

    <%= f.text_field :machine_sn, label: "Serial Number", placeholder: "XXXXPV.", help:"|machine version, number, type|", label_col: "col-sm-2", control_col: "col-sm-3"  %>
	
  	<%= f.collection_select(:box_id, Box.all, :id, :box_sn, label: "Box", label_col: "col-sm-2", control_col: "col-sm-2") %>
	
	<%= f.date_select :installdate, label: "Install Date", label_col: "col-sm-2", control_col: "col-sm-6" %>
  
<%= f.form_group do %>
    <div class="well col-md-4" >
      <%= f.submit class: "btn btn-default" %>    
      <%= link_to "Cancel", machines_path(@machine), class: "btn btn-default" %>
    </div>
 <% end %>
<% end %>

app/views/machines/_infobox.html.erb
 <div class = "panel panel-default">
   <div class = "panel-heading"> 
      <p>Machine Information</p>
   </div>
    <div class =  "panel-body">
        <h2>Machine: <%= @machine.box.board.board_sn %></h2>
        <h3>Box: <%= @machine.box.box_sn %></h3>
        <h3>Firmware Version: <%= @machine.box.board.firmware %></h3>
        
     <div class = "well" >
            <%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit Machine'.html_safe, edit_machine_path(@machine), class: "btn btn-default" %> 
            <%= link_to '<i class="glyphicon glyphicon-pencil"></i> FAT Test'.html_safe, new_machine_fat_test_path(@machine, @fat_test), class: "btn btn-default" %></td>
        </div>
    </div>
</div>  

app/views/machines/_machinelogs.html.erb
<h3>Machine Logs</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Observation</th>
      <th>Action</th>
      <th>Assigned To</th>
	  <th>Date Submitted</th>    
      <th>Status</th>    
      <td>&nbsp;</td>
    </tr>
  </thead>
   <% if @machine.logs.count > 0 %>
    
    <% @machine.logs.order([created_at: :desc]).each do |log| %>
    
        <% if log.status == "open"  %>
            <tr class="warning row-fluid">
            <td><%= log.observation %></td>
            <td><%= log.action %></td>
		    <td><%= log.assignedtouser %></td>
            <td><%= log.created_at.strftime("%F") %></td>
            <td><%= log.status.humanize %></td>    
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i> View'.html_safe, machine_log_path(@machine, log), class: "btn" %><%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_machine_log_path(@machine, log), class: "btn" %></td> 
            </tr>
        <% else %>
            <tr class="default row-fluid">
            <td><%= log.observation %></td>
            <td><%= log.action %></td>
		    <td><%= log.assignedtouser %></td>
			<td><%= log.created_at.strftime("%F") %></td>
            <td><%= log.status.humanize %></td>  
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i> View'.html_safe, machine_log_path(@machine, log), class: "btn" %><%= link_to '<i class="glyphicon glyphicon-pencil"></i> Edit'.html_safe, edit_machine_log_path(@machine, log), class: "btn" %></td> 
                </tr>
             <% end %>
    
    <% end %>
  <% else %>
    <tr>
      <td colspan="7">No logs found for this machine.  Click the 'New Log' button to create a new log.</td>
    </tr>
  <% end %>
</table>

app/views/machines/_statusbox.html.erb
 <div class = "panel panel-default">
   <div class = "panel-heading"> 
      <p>Status Information</p>
   </div>
    <div class =  "panel-body">
        <h3>Machine Status:  <%= @machine.servicestatus %> </h3>
        <h3>Box Status: <%= @machine.box.servicestatus %> </h3>
        <h3>Board Status: <%= @machine.box.board.servicestatus %> </h3>
    </div>
</div>  

app/views/machines/create.html.erb
<h1>Machines#create</h1>
<p>Find me in app/views/machines/create.html.erb</p>

app/views/machines/edit.html.erb
<h1>Editing Machine: <%= @machine.machine_sn %></h1>
<%= render "form" %>

app/views/machines/index.html.erb
<h1>Machines</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Machine SN</th>
      <th>Box SN</th>
      <th>Site</th> 
	  <th>Location</th>   
      <th>Service Status</th>    
      <th>Number of Logs</th>
	  <th>Created On</th>
      <th>Last Update</th>
    </tr>
  </thead>
  <tbody>
    <% if @machines.count == 0 %>
      <tr>
        <td colspan="7">
          No machines found. Click the button below to add a new one.
        </td>
      </tr>
    <% else %>
      <% @machines.each do |machine| %>

          <tr class = "default">
              <td><%= link_to "#{machine.machine_sn}", machine %></td>
              <td><%= machine.box.box_sn %></td>
              <td><%= machine.site.sitename %></td>
			  <td><%= machine.site.latitude %>, <%= machine.site.longitude %></td>
              <td><%= machine.servicestatus %></td>
              <td><%= machine.logs.count %></td>
			  <td><%= machine.created_at.strftime("%F") %></td>
              <td><%= machine.updated_at.strftime("%F") %></td>
          </tr>

      <% end %>
    <% end %>
  </tbody>
</table>

<div class="well">
<%= link_to "New Machine", new_machine_path, class: "btn btn-default" %>
</div>

app/views/machines/new.html.erb
<h1>Create a New Machine</h1>
<%= render "form" %>

app/views/machines/show.html.erb
<div class= "row">
    <div class= "col-md-6">
      <%= render "infobox"%>
    </div>
    <div class= "col-md-6">
      <%= render "statusbox"%>
    </div>     
</div>   



<hr />
 
<%= render "machinelogs" %>


<div class="well">
  <%= link_to "New Log", new_machine_log_path(@machine), class: "btn btn-default" %>
  <%= link_to "Back to Machines", machines_path(@machines), class: "btn btn-default" %>      
</div>

app/views/machines/update.html.erb
<h1>Machines#update</h1>
<p>Find me in app/views/machines/update.html.erb</p>