config/routes.rb
Rails.application.routes.draw do

  resources :fat_tests

  devise_for :users
    
  resources :boards do
    resources :boxes   
    resources :logs
  end

  resources :boxes do
    resources :boards
    resources :machines  
    resources :logs
  end
    
  resources :machines do
    resources :boxes
    resources :boards 
    resources :logs
    resources :fat_tests 
  end    

  resources :sites do
    resources :machines    
    resources :boxes 
    resources :boards  
    resources :logs 
  end 

  resources :customers do
    resources :machines    
    resources :boxes  
  end 
  
         
    
  root to: "machines#index"
    
end    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Solaflect Internal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar nav-tabs navbar-inverse navbar-static-top">
    <div class="container">
        <h5>Solaflect Service Database - v5.2</h5>
      <ul class="nav navbar-nav">
          <li><%= link_to "Boards",boards_path %></li>
          <li><%= link_to "Boxes", boxes_path %></li>
          <li><%= link_to "Machines", machines_path %></li>
		  <li><%= link_to "Customers", customers_path %></li> 
          <li><%= link_to "Sites", sites_path %></li> 
          </ul>
          <ul class="nav navbar-nav navbar-right">   
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
          </ul>     
    </div>
  </nav>
   
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>